### ISSUE TITLE
Não consigo "rodar" hibernate do jeito "correto"!

### ISSUE THREAD

**Issue by TiagoEngBrazil** [cami-la/credit-request-system#1]
Olá, Camila,

Coloquei as linhas de comando:

jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true

no arquivo .yml e o BD não funciona!
Só funciona com as linhas:

  jpa:
    hibernate:
      ddl-auto: create-drop

**Comment by cami-la** [comment]
Olá, @TiagoEngBrazil. Tudo bem? (:

Me tira algumas dúvidas:

1. Qual a versão do Spring Boot você está utilizando?
2. Você está com o flyway direitinho no projeto e com as migrations?

Pergunto isso porque aqui está funcionando direitinho:

![intellij-h2console](https://github.com/cami-la/credit-request-system/assets/64323124/c216ca5e-54c7-4d70-8aed-1feb9bd71848)

A opçãp do **jpa.hibernate.ddl-auto: create-drop** você está pedindo para o Hibernate criar as tabelas de entidade assim que o sistema iniciar e quando você para o sistema, apagar tudo.
Com as migrations, não precisaria. Já que com os arquivos versionados, o flyway irá ler os arquivos `.sql` que já têm as instruções:

![migrations](https://github.com/cami-la/credit-request-system/assets/64323124/bc28a285-a33b-482b-b2d1-8f08987bfde2)

Dá uma olhadinha no meu projeto e vê se as configurações são as mesmas: https://github.com/cami-la/credit-application-system

Lembrando que o arquivo application.yml precisa estar bem identado, ok? Caso contrário, acontecem alguns erros inesperados:

```yml
spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: cami
    password:
  jpa:
    show-sql: true
    #hibernate:
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
```
